clear N3_fcc; 
clc
commandwindow
out_path = '../../../mtlb/N3/smlk/';

mex CXXFLAGS='$CXXFLAGS -std=c++2a -D GNC_BAREMETAL' ...
    -I'../../core/inc'  ...
    N3_fcc.cpp         ...
    ../tst/debug.cpp    ... 
    ../fcc.cpp          ... 
    ../fcc_alg.cpp      ... 
    ../../core/src/geom/quaternion.cpp   ... 
    ../../core/src/navs/details.cpp      ...
    ../../core/src/navs/eci.cpp          ...
    ../../core/src/navs/orb.cpp          ...
    ../../core/src/navs/wgs84.cpp        ...
    ../../core/src/geom/dcm.cpp          ...
    ../../core/src/geom/euler.cpp;
	
copyfile('N3_fcc.mexa64', strcat(out_path, 'N3_fcc.mexa64'));
cd(out_path)
